# You must run "make env" (at the root level) before these stages will run
stages:
{%- for res in results %}
  build-case-{{res}}:
    wdir: results
    cmd: 
      - omc {{res}}.mos
      - rm {{res}}_*.c {{res}}.c {{res}}.o {{res}}_*.h {{res}}_*.o {{res}}.libs {{res}}.log {{res}}.makefile {{res}}_prof*
    deps:
      - ../build-arch
      - {{res}}.mos
      - ../../ModelicaByExample
    outs:
      - {{res}}_info.json
      - {{res}}_init.xml
      - {{res}}_res.mat
      - {{res}}
{%- endfor %}
{%- for res in results %}
  build-wasm-case-{{res}}:
    wdir: results
    cmd:
      - omc {{res}}-wasm.mos
    deps:
      - {{res}}-wasm.mos
      - ../../ModelicaByExample
    outs:
      - wasm/dylink/{{res}}.fmu
      - wasm/component/{{res}}.fmu
{%- endfor %}
{%- for res in results %}
  build-wasm-aot-{{res}}:
    wdir: results
    cmd:
      - node ../../tools/wasm/transpile.mjs --fmu wasm/component/{{res}}.fmu --out wasm/aot/{{res}}
    deps:
      - wasm/component/{{res}}.fmu
      - ../../tools/wasm/transpile.mjs
    outs:
      - wasm/aot/{{res}}
{%- endfor %}
  build-exes:
    wdir: results
    cmd:
      - tar cf exes.tar.gz {% for res in results %} {{ res }} {% endfor %}
    deps:
{%- for res in results %}
      - {{res}}
{%- endfor %}
    outs:
      - exes.tar.gz
