#!/usr/bin/env node
// MIC-84 / MIC-87 — adapt the pipeline's per-case metadata into <SimFigure>'s
// case contract. text/results/json/<res>-case.json is already ~exactly the Astro
// schema (from the specs DSL); we just add params:[] and emit src/cases/<res>.json
// plus an index.ts that exposes them as `cases[id]`.
import fs from 'node:fs';
import path from 'node:path';

const SRC = '../text/results/json';
const OUT = 'src/cases';
fs.mkdirSync(OUT, { recursive: true });

const files = fs.existsSync(SRC) ? fs.readdirSync(SRC).filter((f) => f.endsWith('-case.json')) : [];
const ids = [];
for (const f of files) {
  const j = JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8'));
  const id = j.res || f.replace(/-case\.json$/, '');
  if (!j.params) j.params = [];              // Astro schema adds editable params (none by default)
  fs.writeFileSync(path.join(OUT, `${id}.json`), JSON.stringify(j, null, 2) + '\n');
  ids.push(id);
}
// dedupe (a res id can appear in more than one -case.json) so index.ts has no
// duplicate identifiers
const seen = new Set();
const uniq = ids.filter((id) => (seen.has(id) ? false : (seen.add(id), true))).sort();
ids.length = 0; ids.push(...uniq);

const safe = (id) => 'c_' + id.replace(/[^A-Za-z0-9_]/g, '_');
const index = `// AUTO-GENERATED by tools/build-cases.mjs — do not edit.
// The structured figure contract consumed by <SimFigure> (data-case).
export interface CaseVar { name: string; scale: number; legend: string; style: string }
export interface CaseParam { key: string; label: string; default: string | number; editable: boolean }
export interface CaseData {
  res: string; name: string; title: string;
  stopTime: number | null; tol: number; ncp: number;
  mods: Record<string, unknown>; params: CaseParam[]; vars: CaseVar[];
  ylabel?: string; legloc?: string; ncols?: number; type?: string;
}
${ids.map((id) => `import ${safe(id)} from './${id}.json';`).join('\n')}

export const cases: Record<string, CaseData> = {
${ids.map((id) => `  ${JSON.stringify(id)}: ${safe(id)} as CaseData,`).join('\n')}
};
`;
fs.writeFileSync(path.join(OUT, 'index.ts'), index);
console.log(`wrote ${ids.length} case JSONs + index.ts`);
