# FROM ghcr.io/mtiller/book-builder-image:latest
FROM ghcr.io/mtiller/book-builder-image:latest

# # Add a normal user
# RUN useradd -m  -s /bin/bash ubuntu
# # RUn mkdir /etc/sudoers.d
# RUN usermod -aG sudo ubuntu && echo "ubuntu ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ubuntu
# RUN chmod 0440 /etc/sudoers.d/ubuntu
# USER ubuntu:ubuntu

# # Install 
# RUN mkdir -p /home/ubuntu/.openmodelica/libraries
