# FROM ghcr.io/mtiller/book-builder-image:latest
FROM ghcr.io/mtiller/book-builder-image:v0.1.3

# Use the non-root user?
# USER ubuntu:ubuntu

# # Install 
# RUN mkdir -p /home/ubuntu/.openmodelica/libraries
